name: Deployment

on:
  push:
    branches: [source] # only push events on source branch trigger deployment

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        hexo clean
        hexo g
    - name: Deploy to Github Pages
      env:
        GIT_NAME: onedayrex
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/onedayrex/onedayrex.github.io.git
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global init.defaultBranch master
        cd ./public && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m ":rocket:auto build sucessful"
        git push --force --quiet "https://$GH_TOKEN@$REPO" master:master